(() => {
const SHEET_ID="1Nf4lJrYxoao-Z83RHCxLD3eUAvQGqJj7aDwWuIEV5Hc";
const CSV_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv`;
const grid=document.getElementById("portfolio-grid"),status=document.getElementById("portfolio-status");
const parseCSV=text=>{const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell="";}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;};
const key=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const pick=(obj,names)=>{for(const n of names){const v=obj[key(n)];if(v)return v.trim();}return"";};
const safeUrl=value=>{if(!value)return"";try{const u=new URL(value.startsWith("http")?value:`https://${value}`);return ['http:','https:'].includes(u.protocol)?u.href:"";}catch{return"";}};
const card=p=>{const el=document.createElement("article");el.className="portfolio-card reveal visible";const image=safeUrl(p.image);const link=safeUrl(p.url);el.innerHTML=`<div class="portfolio-image">${image?`<img src="${image.replace(/"/g,'&quot;')}" alt="Screenshot of ${p.name.replace(/"/g,'&quot;')}" loading="lazy">`:`<div class="portfolio-placeholder">${p.name}</div>`}</div><div class="portfolio-body"><h2>${p.name}</h2><p>${p.description||"Website project by Grammer Web Solutions."}</p>${link?`<a class="button button-small" href="${link}" target="_blank" rel="noopener">Visit website</a>`:""}</div>`;return el;};
async function load(){try{const res=await fetch(CSV_URL,{cache:"no-store"});if(!res.ok)throw new Error(`Sheet returned ${res.status}`);const rows=parseCSV(await res.text());if(rows.length<2)throw new Error("No portfolio rows found");const headers=rows[0].map(key);const projects=rows.slice(1).map(row=>{const obj={};headers.forEach((h,i)=>obj[h]=row[i]||"");return {name:pick(obj,["business name","website name","project name","name","title"]),description:pick(obj,["description","project description","summary"]),url:pick(obj,["website url","website link","url","link"]),image:pick(obj,["screenshot","screenshot url","image","image url","thumbnail"]),featured:pick(obj,["featured","show","published","active"])};}).filter(p=>p.name&&!["no","false","0","hidden"].includes(p.featured.toLowerCase()));grid.replaceChildren(...projects.map(card));status.textContent=`${projects.length} project${projects.length===1?"":"s"}`;if(!projects.length)throw new Error("No visible projects found");}catch(error){console.error(error);status.textContent="Portfolio unavailable";grid.innerHTML='<div class="portfolio-empty"><h2>Portfolio projects are being prepared.</h2><p>Please check back soon or contact us to see current work.</p></div>';}}
load();
})();
